---
- name: deploy katuma_reports app
  hosts: ofn_servers
  remote_user: "{{ user }}"
  become: true
  become_user: "{{ unicorn_user }}"

  vars:
    ansistrano_deploy_to: "/home/{{ unicorn_user }}/apps/katuma_reports"
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: git
    ansistrano_git_repo: https://github.com/coopdevs/katuma_reports.git
    ansistrano_git_branch: master
    ansistrano_ensure_shared_paths_exist: yes
    ansistrano_ensure_basedirs_shared_files_exist: yes
    ansistrano_after_update_code_tasks_file: "{{ playbook_dir }}/deploy_hooks/after-code-update.yml"

  roles:
    - role: vendor/carlosbuenosvinos.ansistrano-deploy

  notify:
    - restart katuma_reports_unicorn
