---
- name: Katuma customizations over OFN
  hosts: ofn_servers
  remote_user: "{{ user }}"
  become: true

  roles:
    - role: katuma_reports
      vars:
        app_path: "/home/{{ unicorn_user }}/apps/katuma_reports"
        shared_path: "{{ app_path }}/shared"
        config_path: "{{ shared_path }}/config"
        sockets_path: "{{ shared_path }}/sockets"
        log_path: "{{ shared_path }}/log"
        pids_path: "{{ shared_path }}/pids"
        ofn_route_override: "/admin/reports/order_cycle_management"
