---
- name: Katuma customizations over OFN
  hosts: ofn_servers
  remote_user: "{{ user }}"

  vars:
    prometheus_group: prometheus
    prometheus_user: prometheus
    prometheus_install_path: /opt/prometheus
    prometheus_log_path: /var/log/prometheus
    prometheus_pid_path: /var/run/prometheus
    prometheus_db_path: /var/lib/prometheus
    node_exporter_version: 0.14.0

  roles:
    - role: node-exporter
